app/models.py
from datetime import datetime
import random
from . import db

# Associação muitos-para-muitos entre Record e Tag
record_tag = db.Table(
    "record_tag",
    db.Column("record_id", db.Integer, db.ForeignKey("record.id"), primary_key=True),
    db.Column("tag_id", db.Integer, db.ForeignKey("tag.id"), primary_key=True),
)


def generate_random_color_hex():
    return "#{:06x}".format(random.randint(0, 0xFFFFFF))


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), nullable=False, unique=True)
    password = db.Column(db.String(150), nullable=False)
    records = db.relationship("Record", backref="user", lazy=True)


class Record(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    amount = db.Column(db.Float, nullable=False)
    description = db.Column(db.String(255), nullable=False)
    date = db.Column(db.Date, nullable=False, default=datetime.utcnow)
    created_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    updated_at = db.Column(
        db.DateTime,
        nullable=False,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
    )
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    tags = db.relationship(
        "Tag",
        secondary=record_tag,
        lazy="subquery",
        backref=db.backref("records", lazy=True),
    )


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False, unique=True)
    color_hex = db.Column(
        db.String(7), default=generate_random_color_hex, nullable=False
    )

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_session import Session
from flask_migrate import Migrate
from config import Config

db = SQLAlchemy()
migrate = Migrate()


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    Session(app)
    migrate.init_app(app, db)

    from .routes import routes

    app.register_blueprint(routes)

    return app

app/routes.py
import datetime

from flask import (
    Blueprint,
    flash,
    g,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from werkzeug.security import check_password_hash

from . import db
from .models import Record, Tag, User

routes = Blueprint("routes", __name__)


@routes.before_app_request
def before_request():
    g.user = None
    if "user_id" in session:
        g.user = User.query.get(session["user_id"])


@routes.route("/")
def index():
    if not g.user:
        return redirect(url_for("routes.login"))

    # argumentos esperados
    date_start = request.args.get("date_start")
    date_end = request.args.get("date_end")
    tags = request.args.get("tags") 
    cash_in_out = request.args.get("cash_in_out")

    records = db.session.query(Record)
    # filtrando por data e tags caso esteja presente
    if date_start and date_end:  
        print("Filtrando por data...")  
        records = records.filter(Record.date.between(date_start, date_end))
    if tags:
        print("Filtrando por tags...")
        tags = [tag.strip() for tag in tags.split(",")]
        records = records.filter(Record.tags.any(Tag.name.in_(tags)))
    
    # Filtrando por entradas e saídas
    if cash_in_out == "entradas":
        records = records.filter(Record.amount > 0)
    elif cash_in_out == "saidas":
        records = records.filter(Record.amount < 0)

    records = records.order_by(Record.date.desc()).all()
    # somando todos os valores de registros
    records_sum = sum([record.amount for record in records])
    return render_template("index.html.j2", records=records, sum=records_sum)


@routes.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form["username"]
        password = request.form["password"]

        user = User.query.filter_by(username=username).first()
        if user and check_password_hash(user.password, password):
            session["user_id"] = user.id
            return redirect(url_for("routes.index"))
        else:
            flash("Login Failed. Check your username and/or password.")

    return render_template("login.html.j2")


@routes.route("/logout")
def logout():
    session.pop("user_id", None)
    return redirect(url_for("routes.login"))


@routes.route("/add-record", methods=["POST"])
def add_record():
    if not g.user:
        return redirect(url_for("routes.login"))

    amount_type = request.form["type"]
    amount = request.form["amount"]
    if amount_type == "saida":
        amount = -float(amount)
    description = request.form["description"]
    date = datetime.date.fromisoformat(request.form["date"])
    tags = request.form["tags"].split(",")

    new_record = Record(
        amount=amount, description=description, date=date, user_id=g.user.id
    )
    db.session.add(new_record)
    db.session.commit()

    for tag_name in tags:
        tag = Tag.query.filter_by(name=tag_name.strip()).first()
        if not tag:
            tag = Tag(name=tag_name.strip())
        new_record.tags.append(tag)

    db.session.commit()

    return redirect(url_for("routes.index"))


@routes.route("/edit-record/<int:id>", methods=["GET", "POST"])
def edit_record(id):
    if not g.user:
        return redirect(url_for("routes.login"))

    record = Record.query.get_or_404(id)

    if request.method == "POST":
        amount_type = request.form["type"]
        amount = request.form["amount"]
        if amount_type == "saida":
            amount = -float(amount)
        record.amount = amount
        record.description = request.form["description"]
        record.date = datetime.date.fromisoformat(request.form["date"])
        db.session.commit()

        record.tags.clear()
        tags = request.form["tags"].split(",")

        for tag_name in tags:
            tag = Tag.query.filter_by(name=tag_name.strip()).first()
            if not tag:
                tag = Tag(name=tag_name.strip())
            record.tags.append(tag)

        db.session.commit()
        return redirect(url_for("routes.index"))

    tags = ", ".join([tag.name for tag in record.tags])
    return render_template("edit_record.html.j2", record=record, tags=tags)

app/templates/base.html.j2
<!DOCTYPE html>
<html>

<head>
    <title>Despesas e Investimentos</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
    <header>
        <nav>
            {% if g.user %}
            <a href="{{ url_for('routes.index') }}">Home</a>
            <a href="{{ url_for('routes.logout') }}">Logout</a>
            {% else %}
            <a href="{{ url_for('routes.login') }}">Login</a>
            {% endif %}
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>

app/templates/base.j2
<!DOCTYPE html>
<html>
<head>
    <title>Expenses Tracker</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
    <header>
        <nav>
            {% if g.user %}
                <a href="{{ url_for('routes.index') }}">Home</a>
                <a href="{{ url_for('routes.logout') }}">Logout</a>
            {% else %}
                <a href="{{ url_for('routes.login') }}">Login</a>
            {% endif %}
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
</body>
</html>

app/templates/edit_record.html.j2
{% extends "base.html.j2" %}

{% block content %}
<h1>Edit Record</h1>
<form action="{{ url_for('routes.edit_record', id=record.id) }}" method="post">
    <label for="type">Tipo:</label>
    <select name="type" id="type">
        <option value="entrada" {% if record.amount>= 0 %}selected{% endif %}>Entrada</option>
        <option value="saida" {% if record.amount < 0 %}selected{% endif %}>Saída</option>
    </select><br>
    <label for="amount">Valor:</label>
    <input type="number" name="amount" value="{{ record.amount|abs }}" step="0.01"><br>
    <label for="description">Description:</label>
    <input type="text" id="description" name="description" value="{{ record.description }}" required><br>
    <label for="date">Date:</label>
    <input type="date" id="date" name="date" value="{{ record.date.strftime('%Y-%m-%d') }}" required><br>
    <label for="tags">Tags:</label>
    <input type="text" name="tags" value="{{ tags }}"><br>
    <input type="submit" value="Update Record">
</form>
{% endblock %}

app/templates/edit_record.j2
{% extends "base.j2" %}

{% block content %}
<h1>Edit Record</h1>
<form action="{{ url_for('routes.edit_record', id=record.id) }}" method="post">
    <label for="amount">Valor:</label>
    <input type="float" name="amount" value="{{ record.amount }}" step="0.01"><br>
    <label for="description">Description:</label>
    <input type="text" id="description" name="description" value="{{ record.description }}" required><br>
    <label for="date">Date:</label>
    <input type="date" id="date" name="date" value="{{ record.date|strftime('%Y-%m-%d') }}" required><br>
    <label for="tags">Tags:</label>
    <input type="text" name="tags" value="{{ tags }}"><br>
    <input type="submit" value="Update Record">
</form>
{% endblock %}

app/templates/index.html.j2
{% extends "base.html.j2" %}

{% block content %}
<h1>Olá {{ g.user.username }}</h1>
<form action="{{ url_for('routes.add_record') }}" method="post">
    Tipo:
    <select name="type" id="type">
        <option value="entrada">Entrada</option>
        <option value="saida" selected>Saída</option>
    </select><br>
    Valor: <input type="number" name="amount" step="0.01"><br>
    Descrição: <input type="text" name="description"><br>
    Data: <input type="date" name="date"><br>
    Tags (separe as tags por vírgulas se for mais de uma): <input type="text" name="tags"><br>
    <input type="submit" value="Adicionar Registro">
</form>
<h2>Filtro</h2>
<form action="{{ url_for('routes.index') }}" method="get">
    De: <input type="date" name="date_start"> a <input type="date" name="date_end"><br>
    Tags: <input type="text" name="tags"><br>
    Cash in/out:
    <select name="cash_in_out">
        <option value="">Todos</option>
        <option value="entradas">Entradas</option>
        <option value="saidas">Saídas</option>
    </select><br/>
    <input type="submit" value="Filter">
</form>
<h2>Registros</h2>
{% if sum %}
<strong>Soma: R$ {{ "%.2f"|format(sum) }}</strong>
<br /><br />
{% endif %}
{% if records|length <= 0 %} <p>Não ha registros.</p>
    {% endif %}
    {% if records|length > 0 %}
    <ul>
        {% for record in records %}
        <li>{{ record.date.strftime('%d/%m/%Y') }} - {{ record.description }} - R$ {{ record.amount }} - {% for tag in
            record.tags %}
            <span style="background-color: {{ tag.color_hex }}">{{ tag.name }}</span>
            {% endfor %}
            <a href="{{ url_for('routes.edit_record', id=record.id) }}">Editar</a>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
    {% endblock %}

app/templates/index.j2
{% extends "base.j2" %}

{% block content %}
    <h1>Olá {{ g.user.username }}</h1>
    <form action="{{ url_for('routes.add_record') }}" method="post">
        Valor: <input type="float" name="amount" step="0.01"><br>
        Descrição: <input type="text" name="description"><br>
        Data: <input type="date" name="date"><br>
        Tags (separe as tags por vírgulas se for mais de uma): <input type="text" name="tags"><br>
        <input type="submit" value="Add Record">
    </form>
    <h2>Records</h2>
    <ul>
        {% for record in records %}
            <li>{{ record.date }} - {{ record.description }} - {{ record.amount }} - {% for tag in record.tags %}
            <span style="background-color: {{ tag.color_hex }}">{{ tag.name }}</span>
            {% endfor %}
                <a href="{{ url_for('routes.edit_record', id=record.id) }}">Edit</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

app/templates/login.html.j2
{% extends "base.html.j2" %}

{% block content %}
    <h1>Login</h1>
    <form action="{{ url_for('routes.login') }}" method="post">
        Username: <input type="text" name="username"><br>
        Password: <input type="password" name="password"><br>
        <input type="submit" value="Login">
    </form>
{% endblock %}

app/templates/login.j2
{% extends "base.j2" %}

{% block content %}
    <h1>Login</h1>
    <form action="{{ url_for('routes.login') }}" method="post">
        Username: <input type="text" name="username"><br>
        Password: <input type="password" name="password"><br>
        <input type="submit" value="Login">
    </form>
{% endblock %}